export const CompromisoProyectoConstantes = {
    TAMANO_MAXIMO_COMPROMISO: 1000,
    TAMANO_MAXIMO_COMENTARIO: 1200,
    ID_TIPO_POR_DEFECTO: 15,
    ESTADO_POR_DEFECTO: 'ACTIVO',
    RESULTADO_AUTOMATICO_POR_DEFECTO: 'i',
    META_EN_BPP_POR_DEFECTO: 0,
    ASUMIDO_POR_DEFECTO: 1,
    TITULO_ALERTA_ELIMINAR_COMPROMISO: 'Eliminar compromiso',
    ELIMINAR_COMPROMISO: ' ¿Realmente desea eliminar el compromiso?'
};
