import { Time } from '@angular/common';
import { ProcesoSeleccionIngreso } from './proceso-seleccion-ingreso';
import { FinanciadorConvocatoria } from './financiador-convocatoria';
import { Disponibilidad } from './disponibilidad';

export interface InformacionGeneralConvocatoria {
    identificador?: number;
    codigoFinanciador?: string;
    procesoSeleccion?: ProcesoSeleccionIngreso;
    registrador?: string;
    fechaCreacion?: string;
    fechaPublicacion?: string;
    fechaCierre?: string;
    fechaApertura?: string;
    fechaResultados?: string;
    nombre?: string;
    nombreCorto?: string;
    objetoDescripcion?: string;
    comentario?: string;
    urlDetalle?: string;
    periodoPresupuesto?: string;
    totalPeriodosPresupuesto?: number;
    inicioPeriodoPresupuesto?: string;
    selectorRegistrador?: string;
    maxInicioFormal?: number;
    maxProrrogaIniFormal?: number;
    maxProrrogaEjecucion?: number;
    inicioConNN?: string;
    tiempoParaSuspender?: number;
    maxTiempoSuspendido?: number;
    tiempoParaCancelar?: number;
    maxTieEntCompro?: number;
    maxTieAplazCompro?: number;
    maxTiempoElegible?: number;
    nombreEncuesta?: string;
    horaCierre?: Time;
    estado?: string;
    habilitarRegistro?: boolean;
    listaFinanciadores?: FinanciadorConvocatoria[];
    disponibilidad?: Disponibilidad;
}
