import { InformacionGeneral } from "./informacion-general";
import { InformacionGeneralConvocatoria } from "./informacion-general-convocatoria";
import { ModalidadConvocatoria } from "./modalidad-convocatoria";

export interface InformacionGeneralProyecto {
  codigo: string;
  centroGestion?: number;
  claseProyecto: number;
  comiteBioetica?: number;
  convocatoria?: InformacionGeneralConvocatoria;
  duracion?: number;
  esElegibleJurado?: number;
  estado?: string;
  etapaActual?: number;
  fechaAprobacionRechazo?: number;
  fechaEnvioCentro?: number;
  fechaRegistro?: number;
  instanciaAdmtivaActual?: number;
  lugarEjecucion?: string;
  modalidadConvocatoria?: ModalidadConvocatoria;
  moneda?: string;
  nivelProyecto: number;
  nombreCompleto?: string;
  nombreCorto?: string;
  notificadoRp?: string;
  palabrasClaves?: string;
  pendienteAjustePpto?: number;
  pendienteRevisionCentro?: string;
  periodoCronograma?: string;
  procesoSeleccion?: InformacionGeneral;
  requiereAvalBioetica?: number;
  responsable?: string;
  seccional?: string;
  selectorResponsable?: string;
  selectorSeccional?: string;
  subnivelProyecto?: number;
  subtipoProyecto?: number;
  tipoProyectoMacro?: number;
  tipoProyecto?: number;
}
