import { GrupoInvestigacion } from './grupo-investigacion';
import { RolParticipanteProyecto } from './rol-participante-proyecto';
import { PersonaNatural } from './persona-natural';
import { Vinculo } from './vinculo';
import { PersonaJuridica } from './persona-juridica';
import { Programa } from './programa';
import { Dependencia } from './dependencia';

export interface ParticipanteProyecto {
    identificador: number;
    vinculacionClase: string;
    vinculacionTipo: string;
    dedicacionHoras: number;
    dedicacionMeses: number;
    nombreProgramaExterno: string;
    fechaFin: string;
    porcentajeProgAcad: number;
    vinculacionUdea: string;
    porcentajeBeneficios: number;
    anonimo: number;
    observacion: string;
    codFaculProgApoy: number;
    dedicacionHorasPlan: number;
    codigoDependencia: string;
    funcion: string;
    nombreDependencia: string;
    fechaInicio: string;
    dedicacionMesesPlan: number;
    correo: string;
    codProgramaApoyado: number;
    nombreCompleto: string;
    grupo: number;
    institucion: string;
    proyecto: string;
    personaNatural: string;
    selectorPersona: string;
    rolParticipanteProyecto: number;
    rol: RolParticipanteProyecto;
    participante: PersonaNatural;
    vinculo: Vinculo;
    institucionP: PersonaJuridica;
    programa: Programa;
    grupoInvestigacion: GrupoInvestigacion;
    dependenciaSeleccionada: Dependencia;
    habilitarRegistro: boolean;
}
